# Generated by Django 5.0.6 on 2024-06-25 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('user_nickname', models.CharField(default='', max_length=155, primary_key=True, serialize=False)),
                ('user_name', models.CharField(default='', max_length=155)),
                ('user_email', models.EmailField(default='', max_length=254)),
                ('user_age', models.IntegerField(default=0)),
            ],
        ),
    ]
