# Generated by Django 5.0.6 on 2024-06-25 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro_usuario', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Usuarios',
            new_name='Usuario',
        ),
    ]
