# Generated by Django 5.0.6 on 2024-06-25 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro_usuario', '0002_rename_usuarios_usuario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='user_age',
            new_name='age',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='user_email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='user_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='user_nickname',
            new_name='nickname',
        ),
    ]
