# Generated by Django 5.0.6 on 2024-06-25 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro_usuario', '0003_rename_user_age_usuario_age_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='senha',
            field=models.CharField(default='', max_length=155),
        ),
    ]
